name = "ComplexMixtures"
uuid = "6f35c628-ac57-5bae-8ea9-703a8964f6e9"
authors = ["Leandro Martinez <lmartine@unicamp.br>"]
version = "2.11.3"

[deps]
CellListMap = "69e1c6dd-3888-40e6-b3c8-31ac5f578864"
Chemfiles = "46823bd8-5fb3-5f92-9aa0-96921f3dd015"
ChunkSplitters = "ae650224-84b6-46f8-82ea-d812ca08434e"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FortranFiles = "c58ffaec-ab22-586d-bfc5-781a99fd0b10"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PDBTools = "e29189f1-7114-4dbd-93d0-c5673a921a58"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RandomNumbers = "e6cf234a-135c-5ec9-84dd-332b85af5143"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[weakdeps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
Plotting = "Plots"

[compat]
Aqua = "0.8.9"
BenchmarkTools = "1"
CellListMap = "0.8.30, 0.9"
Chemfiles = "0.10.3"
ChunkSplitters = "3.1"
DelimitedFiles = "1.9"
DocStringExtensions = "0.9.1"
Documenter = "1.3"
FortranFiles = "0.6"
JSON3 = "1.11.1"
LinearAlgebra = "1.9"
PDBTools = "1.8.1, 2"
Plots = "1.39"
PrecompileTools = "1"
Printf = "1.9"
ProgressMeter = "1.10.1"
Random = "1.9"
RandomNumbers = "1.5"
StableRNGs = "1"
StaticArrays = "1.6"
Statistics = "1.9"
StructTypes = "1.10"
Test = "1.9"
TestItemRunner = "0.2"
TestItems = "0.1, 1"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CellListMap = "69e1c6dd-3888-40e6-b3c8-31ac5f578864"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
PDBTools = "e29189f1-7114-4dbd-93d0-c5673a921a58"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "PDBTools", "StaticArrays", "CellListMap", "BenchmarkTools", "TestItemRunner", "Aqua", "DelimitedFiles", "Documenter", "Random", "Plots"]
