name = "ComplexMixtures"
uuid = "6f35c628-ac57-5bae-8ea9-703a8964f6e9"
authors = ["Leandro Martinez <lmartine@unicamp.br>"]
version = "1.0.3-DEV"

[deps]
CellListMap = "69e1c6dd-3888-40e6-b3c8-31ac5f578864"
Chemfiles = "46823bd8-5fb3-5f92-9aa0-96921f3dd015"
ChunkSplitters = "ae650224-84b6-46f8-82ea-d812ca08434e"
CpuId = "adafc99b-e345-5852-983c-f28acb93d879"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FortranFiles = "c58ffaec-ab22-586d-bfc5-781a99fd0b10"
Future = "9fa8497b-333b-5362-9e8d-4d0656e87820"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PDBTools = "e29189f1-7114-4dbd-93d0-c5673a921a58"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RandomNumbers = "e6cf234a-135c-5ec9-84dd-332b85af5143"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[compat]
Aqua = "0.6"
BenchmarkTools = "1"
CellListMap = "0.8.16"
Chemfiles = "0.9, 0.10"
ChunkSplitters = "0.1, 1"
CpuId = "0.3"
DocStringExtensions = "0.8, 0.9"
FortranFiles = "0.6"
JSON3 = "1"
PDBTools = "0.13"
Parameters = "0.12"
PrecompileTools = "1"
ProgressMeter = "1"
RandomNumbers = "1.5"
StableRNGs = "1"
StaticArrays = "1"
StructTypes = "1"
TestItemRunner = "0.2"
TestItems = "0.1"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CellListMap = "69e1c6dd-3888-40e6-b3c8-31ac5f578864"
PDBTools = "e29189f1-7114-4dbd-93d0-c5673a921a58"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "PDBTools", "StaticArrays", "CellListMap", "BenchmarkTools", "TestItemRunner", "Aqua"]
