name = "ComplexMixtures"
uuid = "6f35c628-ac57-5bae-8ea9-703a8964f6e9"
authors = ["Leandro Martinez <lmartine@unicamp.br>"]
version = "0.5.6"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Chemfiles = "46823bd8-5fb3-5f92-9aa0-96921f3dd015"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PDBTools = "e29189f1-7114-4dbd-93d0-c5673a921a58"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Future = "9fa8497b-333b-5362-9e8d-4d0656e87820"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
FortranFiles = "c58ffaec-ab22-586d-bfc5-781a99fd0b10"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ThreadPools = "b189fb0b-2eb5-4ed4-bc0c-d34c51242431"

[compat]
JSON3 = "1"
StructTypes = "1"
Chemfiles = "0.9"
StableRNGs = "1"
DocStringExtensions = "0.8"
ProgressMeter = "1"
PDBTools = "0.12"
StaticArrays = "1"
julia = "1.6"
Parameters = "0.12"
FortranFiles = "0.6"
ThreadPools = "1"
